### PR TITLE
Add BitcoinUnlimited in the peer graph

### PR DESCRIPTION
**Pull request by quentinlesceller**

### CODE REVIEW

**Comment by craigwatson** [comment]
Thanks for the PR, admittedly the code doing the stats generation and display is pretty gnarly!

I have one slight alteration for you - can you add the Unlimited entry at the end of the arrays?

I'm going to be offline for two weeks from Friday (10th February) - in case you commit later than that, I'll pick things up when I'm back online :)

**Comment by quentinlesceller** [comment]
Done!

**Comment by GoneUp** [comment]
ping @craigwatson - want it also ^^

**Comment by craigwatson** [comment]
Apologies for the delay in getting this merged!

**Pull request merged**
